# Generated by Django 3.1.1 on 2020-12-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconverterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='wiki_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
